### PR TITLE
no more pinning werkzeug

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

bump version

### CODE REVIEW

**Comment by AlbertDeFusco** [comment]
@conda-forge-admin, please rerender

**Comment by AlbertDeFusco** [comment]
@conda-forge/core, thanks for pointing out the original wasn't from a fork. I'm still having issues with the renderer.

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by scopatz** [comment]
Seems like rerender bot is back up

**Comment by AlbertDeFusco** [comment]
yay! Thanks for you help.

**Pull request merged**
