### PR TITLE
no more pinning werkzeug

### PR DESCRIPTION
**Pull request by AlbertDeFusco**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

ready

### CODE REVIEW

**Comment by AlbertDeFusco** [comment]
@conda-forge-admin, please rerender

**Comment by AlbertDeFusco** [comment]
hi @conda-forge/core, something went wrong with the rerender.

I see that autotik attempted to make a new PR. I need to change a pin in meta.yaml, how could I add a commit to the autotik PR?

**Comment by scopatz** [comment]
I'll fix the rerender bot, one moment.

**Comment by scopatz** [comment]
Try again in 5 - 10 min

**Comment by AlbertDeFusco** [comment]
Great! Thanks.

**Comment by AlbertDeFusco** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
FYI I don't think this PR came from a fork. Please use a fork to create PRs.

**Comment by scopatz** [comment]
Oh yeah, you need to always create from a fork.  There are docs about that somewhere...

**Pull request closed without merging**
